--- #YAML:1.0
name:               Catalyst-Plugin-Static-Simple-ByClass
version:            0.003
abstract:           locate static content in @INC
author:
    - Peter Karman <karman@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Plugin::Static::Simple:  0.29
    Catalyst::Runtime:    5.8
    Class::Inspector:     0
    Path::Class:          0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
